# Generated by Django 6.0.1 on 2026-01-28 13:49

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='רחוב')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='עיר')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='מיקוד')),
                ('country', django_countries.fields.CountryField(default='IL', max_length=2, verbose_name='מדינה')),
                ('customer_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='מספר לקוח')),
                ('customer_type', models.CharField(choices=[('private', 'פרטי'), ('business', 'עסקי')], default='private', max_length=20, verbose_name='סוג לקוח')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='שם משפחה')),
                ('id_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='תעודת זהות חייבת להכיל 9 ספרות', regex='^\\d{9}$')], verbose_name='תעודת זהות')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='חברה')),
                ('business_number', models.CharField(blank=True, max_length=20, verbose_name='ח.פ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='טלפון')),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='נייד')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
            ],
            options={
                'verbose_name': 'לקוח',
                'verbose_name_plural': 'לקוחות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='רחוב')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='עיר')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='מיקוד')),
                ('country', django_countries.fields.CountryField(default='IL', max_length=2, verbose_name='מדינה')),
                ('company_name', models.CharField(max_length=200, verbose_name='שם החברה')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='טלפון')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='מספר רישיון')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
            ],
            options={
                'verbose_name': 'מתקין',
                'verbose_name_plural': 'מתקינים',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='רחוב')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='עיר')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='מיקוד')),
                ('country', django_countries.fields.CountryField(default='IL', max_length=2, verbose_name='מדינה')),
                ('name', models.CharField(max_length=200, verbose_name='שם הספק')),
                ('supplier_type', models.CharField(choices=[('equipment', 'ציוד'), ('service', 'שירות'), ('other', 'אחר')], default='equipment', max_length=20, verbose_name='סוג ספק')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='טלפון')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
            ],
            options={
                'verbose_name': 'ספק',
                'verbose_name_plural': 'ספקים',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='שם')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='תפקיד')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='טלפון')),
                ('is_primary', models.BooleanField(default=False, verbose_name='איש קשר ראשי')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='לקוח')),
                ('installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.installer', verbose_name='מתקין')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.supplier', verbose_name='ספק')),
            ],
            options={
                'verbose_name': 'איש קשר',
                'verbose_name_plural': 'אנשי קשר',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
