# Generated by Django 6.0.1 on 2026-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-is_primary', 'first_name'], 'verbose_name': 'איש קשר', 'verbose_name_plural': 'אנשי קשר'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='ff', max_length=200, verbose_name='שם פרטי'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='ff', max_length=200, verbose_name='שם משפחה'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='שם'),
        ),
    ]
