# Generated by Django 6.0.1 on 2026-01-29 09:06

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_alter_contact_options_remove_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='מספר חוזה')),
                ('contract_type', models.CharField(choices=[('monitoring', 'ניטור'), ('leads', 'לידים'), ('maintenance', 'תחזוקה')], max_length=20, verbose_name='סוג חוזה')),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('sent', 'נשלח'), ('approved', 'אושר'), ('revise', 'עבר גרסה'), ('lost', 'אבוד')], default='draft', max_length=20, verbose_name='סטטוס')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='שווי החוזה')),
                ('payment_terms', models.TextField(blank=True, verbose_name='תנאי תשלום')),
                ('document', models.FileField(blank=True, upload_to='contracts/', verbose_name='מסמך חוזה')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.customer', verbose_name='לקוח')),
            ],
            options={
                'verbose_name': 'חוזה',
                'verbose_name_plural': 'חוזים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='רחוב')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='עיר')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='מיקוד')),
                ('country', django_countries.fields.CountryField(default='IL', max_length=2, verbose_name='מדינה')),
                ('lead_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='מספר ליד')),
                ('lead_source', models.CharField(blank=True, choices=[('web', 'אתר'), ('phone', 'טלפון'), ('facebook', 'פייסבוק'), ('referral', 'הפנייה'), ('other', 'אחר')], verbose_name='מקור ליד')),
                ('status', models.CharField(choices=[('new', 'חדש'), ('quote', 'הצעת מחיר'), ('won', 'הומר'), ('lost', 'אבוד')], default='new', max_length=20, verbose_name='סטטוס')),
                ('contact_name', models.CharField(max_length=200, verbose_name='שם איש קשר')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין. פורמט: 05XXXXXXXX', regex='^05\\d{8}$')], verbose_name='טלפון')),
                ('estimated_system_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='גודל מערכת משוער (kWp)')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='בעלים')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer', verbose_name='לקוח (לאחר המרה)')),
            ],
            options={
                'verbose_name': 'ליד',
                'verbose_name_plural': 'לידים',
                'ordering': ['-created_at'],
            },
        ),
    ]
